config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  resources :patients

  resources :doctors do 
    resources :appointments
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy 
  has_many :patients, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end 
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :patients

  def full_name
    "#{self.first_name} #{self.last_name}"
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home]

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor
  before_action :set_appointment, only: [:show, :edit, :update, :destroy] 


  def index
    # @patient = current_user.full_name 
    @appointments = @doctor.appointments 
  end

  def show
    # @patient = @appointment.patients.find([:id])
    # @doctor = @appointment.doctors.find([:doctor_id])
  end

  def new
    # @users = User.all - @doctor.users 
    @appointment = @doctor.appointments.new
  end

  def create 
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save 
      redirect_to doctor_appointments_path(@doctor)
    else 
      render :new 
    end 
  end 

  def edit
  end
  
  
  def update 
    if @appointment.update(appointment_params)
      redirect_to doctor_appointment_path(@appointment)
    else 
      render :edit
    end 
  end 

  def destroy
    @appointment.destroy
    redirect_to doctor_appointments_path(@doctor)
  end 

  private 
  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end 

  def appointment_params
    params.require(:appointment).permit(:appointment_date, :appointment_time, :patient_id)
  end 

  def set_appointment
    @appointment = @doctor.appointments.find(params[:id])
  end 
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  def index
    @doctors = Doctor.all 
  end

  def show
  end

  def new
    @doctor = Doctor.new 
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save 
      redirect_to doctors_path 
    else 
      render :new 
    end  
  end 

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor 
    else 
      render :edit 
    end 
  end 

  def destroy
    @doctor.destroy 
    redirect_to doctors_path 
  end 

  private 
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end 

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name) 
  end 
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index
    @patients = Patient.all.order("last_name")
  end

  def show
    @appointments = @patient.appointments
  end

  def new
    @patient = Patient.new 
  end

  def create 
    @patient = Patient.new(patient_params)

    if @patient.save 
      redirect_to @patient 
    else 
      render :new 
    end 
  end 

  def edit
  end
  
  def update 
    if @patient.update(patient_params)
      redirect_to @patient 
    else 
      render :edit 
    end 
  end 

  def destroy 
    @patient.destroy 
    redirect_to patients_path 
  end 

  private 
  def set_patient
    @patient = Patient.find(params[:id])
  end 

  def patient_params 
    params.require(:patient).permit(:first_name, :last_name)
  end 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: @appointments, local: true) do |f| %>
<div class="field">
  <%= f.label :appointment_date %>
  <%= f.text_field :appointment_date, autofocus: true, required: true, placeholder: "Appointment Date" %>
</div>
<div class="field">
  <%= f.label :appointment_time %>
  <%= f.text_field :appointment_time, required: true, placeholder: "Appointment Time" %>
</div>
<div class="field">
  <%= f.label :patient_id %>
  <%= f.text_field :patient_id, required: true, placeholder: "Patient ID" %>
</div>
<div class="action">
  <%= f.submit nil, class: "btn" %>
</div>
<%end%>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>
<p>Please fill your information below:</p>
<%= render "form"%>
<%= link_to 'Cancel', doctor_appointments_path(@doctor, @appointment) %>

<%# TO DO -- MAKE PATH TO CANCEL WORK %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>
<p>Please fill your information below:</p>
<%= render "form"%>
<%= link_to 'Cancel', doctor_appointments_path(@doctor) %>

app/views/appointments/show.html.erb
<h1>Appointments</h1>
<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor), class: "btn" %>
<hr>
<ul>
  <% @doctor.appointments.each do |appointment| %>
    <li>
      <%= appointment.patient_id %>
      <%= appointment.appointment_date%> at 
      <%= appointment.appointment_time%>
    </li>
  <% end %>
</ul>

<%# TO DO == GET PATIENT NAME USING THE ID %>

app/views/doctors/_form.html.erb
<%= form_with(model: @doctor, local: true) do |f| %>
<div class="field">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, autofocus: true, required: true, placeholder: "First Name" %>
</div>
<div class="field">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
</div>
<div class="action">
  <%= f.submit nil, class: "btn" %>
</div>
<%end%>

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>
<p>Please fill your information below:</p>
<%= render "form"%>
<%= link_to 'Cancel', doctors_path %>

app/views/doctors/index.html.erb
<h1>DPL Clinic's Doctors</h1>
<p>Number of Doctors: <%= @doctors.count%><p>
<%= link_to 'Add a Doctor', new_doctor_path, class: "btn"%>
<hr />
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.full_name, doctor_path(doctor), class: "btn" %>| 
      <%= link_to "Edit Doctor", edit_doctor_path(doctor), class: "btn" %>| 
      <%= link_to 'Remove', {:controller => :doctors, :action => 'destroy', :id => doctor.id }, :method => :delete, class:"btn" %>
    </li>
<% end %>
</ul>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>
<p>Please fill your information below:</p>
<%= render "form"%>
<%= link_to 'Cancel', doctors_path %>

app/views/doctors/show.html.erb
<h1><%= @doctor.full_name%>'s Appointments</h1>
<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor), class: "btn" %>
<hr>
<ol>
  <% @doctor.appointments.each do |appointment| %>
    <li>
      <%= appointment.appointment_date%> at 
      <%= appointment.appointment_time%>
      <%= link_to 'More Info', doctor_appointment_path(@doctor, appointment), class: "btn" %>
    </li>
  <% end %>
</ol>

app/views/layouts/_navbar.html.erb
  <div id="user_nav" class="nav-wrapper">
  <% if current_user %>
    
    <%= link_to "Home", root_path, class:"btn deep-purple"%>
    <%= link_to "Doctors", doctors_path, class: "btn deep-purple"%>
    <%= link_to "Patients", patients_path, class: "btn deep-purple"%>
    <div class="right">
    Logged In |
    <%= link_to "Edit User", edit_user_registration_path, class: "btn deep-purple"%>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn blue" %>
    </div>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn deep-purple" %> |
    <%= link_to "Sign in", new_user_session_path, class: "btn deep-purple" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorAppointments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: @patient, local: true) do |f| %>
<div class="field">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, autofocus: true, required: true, placeholder: "First Name" %>
</div>
<div class="field">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
</div>
<div class="action">
  <%= f.submit nil, class: "btn" %>
</div>
<%end%>

app/views/patients/edit.html.erb
<h1>Edit Information</h1>
<p>Please fill your information below</p>
<%= render "form"%>
<%= link_to 'Cancel', patients_path %>

app/views/patients/index.html.erb
<h1>DPL Clinic's Patients</h1>
<p>Number of Patients: <%= @patients.count%><p>
<%= link_to 'New Patient', new_patient_path, class: "btn"%>
<hr />
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to patient.full_name, patient, class: "btn" %>| 
      <%= link_to "Edit Patient", edit_patient_path(patient), class: "btn" %>| 
      <%= link_to 'Remove', {:controller => :patients, :action => 'destroy', :id => patient.id }, :method => :delete, class:"btn" %>
    </li>
    <br>
<% end %>
</ul>
<br>

app/views/patients/new.html.erb
<h1>New Patient</h1>
<p>Please fill your information below</p>
<%= render "form"%>
<%= link_to 'Cancel', patients_path %>

app/views/patients/show.html.erb
<h1>Patient Chart</h1>
<h3>Your information: </h3>
<table class="stripped">
<tr>
    <td>First Name:</td>
    <td><%= @patient.first_name %></td>
</tr>
<tr>
    <td>Last Name:</td>
    <td><%= @patient.last_name %></td>
</tr>
<% @appointments.each_with_index do |appointment, index| %>
<tr>
    <td>Doctor's Name: </td>
    <td><%= appointment.doctor.full_name %></td>
</tr>
<%end%>
<tr>
    <td>Remove Patient:</td>
    <td><%= button_to 'Delete', {:controller => :patients, :action => 'destroy', :id => @patient }, :method => :delete, class:"btn" %></td>
</tr>
</table>


  <%# In appointment index - do @appointments.each_with_index do |appt, i|  %>
  <%# appt.user_id.user.full_name %>
 

app/views/static_pages/home.html.erb
<h1>Welcome to DPL Clinic</h1>
<p>Navigate through the menu to schedule an appointment or view your appointments</p>